#!/bin/sh /etc/rc.common
# Copyright (C) 2007-2012 OpenWrt.org

#touch /tmp/dhcpd.leases
#rm -f /tmp/dhcpd.pid
#dhcpd -cf /ugw/sh/init_scripts/dhcpd.conf -pf /tmp/dhcpd.pid -lf /tmp/dhcpd.leases

START=59

USE_PROCD=1
PROG=/usr/sbin/dhcpd

ADD_LOCAL_DOMAIN=1
ADD_LOCAL_HOSTNAME=1

CONFIGFILE="/var/etc/dhcpd.conf"
PIDFILE="/tmp/dhcpd.pid"
LEASEFILE="/tmp/dhcpd.leases"

service_triggers()                                                            
{                                                                             
	procd_add_reload_trigger "dhcp"                               
}                                                               

boot() {
# Will be launched through hotplug
	return 0
}  

start_service() {
	include /lib/functions

	mkdir -p $(dirname $CONFIGFILE)
	touch /tmp/dhcpd.leases
	rm /etc/rc.d/S60dnsmasq /etc/init.d/dnsmasq
	/usr/bin/lua /usr/sbin/gen_dhcpd_conf.lua

	procd_open_instance
	procd_set_param command $PROG -q -cf $CONFIGFILE -pf $PIDFILE -lf $LEASEFILE
	procd_set_param file $CONFIGFILE
	procd_set_param respawn
	procd_close_instance
}

reload_service() {
	rc_procd stop_service "$@"
	rc_procd start_service "$@"
	return 0
}

stop_service() {
	kill -HUP `cat $PIDFILE`
	rm -f $PIDFILE
	return 0
}
