#!/bin/sh /etc/rc.common

START=11

service_triggers()                                                            
{                                                                             
	echo "nothing"               
}                                                               

boot() {
	/usr/bin/lua /usr/sbin/modify_ucitrack.lua
}  

start_service() {
	/usr/bin/lua /usr/sbin/modify_ucitrack.lua
}

reload_service() {
	echo "nothing"
}

stop_service() {
	echo "nothing"
}
